export const UI_APP_STATE_INIT                      = 'UI_APP_STATE_INIT';
export const UI_APP_STATE_SERVER_CONNECTED          = 'UI_APP_STATE_SERVER_CONNECTED';
export const UI_APP_STATE_SERVER_DISCONNECTED       = 'UI_APP_STATE_SERVER_DISCONNECTED';
export const UI_APP_STATE_LOGGED_IN                 = 'UI_APP_STATE_LOGGED_IN';
export const UI_APP_STATE_LOGGED_OUT                = 'UI_APP_STATE_LOGGED_OUT';
export const UI_APP_STATE_ACTIVE_SESSION            = 'UI_APP_STATE_ACTIVE_SESSION';
